"""initial schema: users, projects, statuses, ranks

Revision ID: 5445ea41d703
Revises: 
Create Date: 2026-07-10 01:29:32.244967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5445ea41d703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active_flag', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('project_no', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.Column('estimate_no', sa.String(length=64), nullable=True),
    sa.Column('amount_excl_tax', sa.Integer(), nullable=True),
    sa.Column('completion_month', sa.String(length=7), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('maintenance_start', sa.Date(), nullable=True),
    sa.Column('maintenance_end', sa.Date(), nullable=True),
    sa.Column('sales_rep', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('project_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('statuses')
    op.drop_table('ranks')
    # ### end Alembic commands ###
